### ISSUE TITLE
guacd issue

### ISSUE THREAD

**Issue by sahara101** [abesnier/docker-guacamole#25]
Hi, 

for some time I have connection issues to guacamole and need to try the connection several times until it works, also once it works it can break with network connection seems unstable. 

The error I receive in logs is: 

11:18:47.360 [Thread-2] ERROR o.a.g.w.GuacamoleWebSocketTunnelEndpoint - Connection to guacd terminated abnormally: Connection to guacd timed out.

What could I do? 

Thanks!

**Comment by yauyauwind** [comment]
Me2 and guacamole via reverse proxy, do this related??

**Comment by sahara101** [comment]
Ah yes, it is also behind reverse proxy and behind authelia
It is that it worked before

**Comment by sahara101** [comment]
Same issue even after the last 2 updates.

**Comment by abesnier** [comment]
that's strange. if it used to work, nothing should change. the images are only rebuilt weekly to keep the inner packages up to date, and guacamole itself has not been updated since July.

did it stop working after you started using the reverse proxy? 

could you post a longer extract of the logs, and your docker-compose or docker command line?

**Comment by sahara101** [comment]
Oh wow, seems I forgot to reply. It is working now without issues. If I remember correctly it was an issue with pi-alert which made my network slow/unstable. 

I will close this now :)
