### ISSUE TITLE
new config won't start up (postgresql.conf not found)

### ISSUE THREAD

**Issue by quorn23** [abesnier/docker-guacamole#3]
**Describe The Bug:**
Fresh installation of the container won't start up properly

**To Reproduce:**
```  guacamole:
    image: abesnier/guacamole
    container_name: guacamole
    hostname: guacamole
    environment:
     - EXTENSIONS=auth-totp
    volumes:
     - ${DOCKERCONFDIR}/guacamole:/config
    ports:
      - 9010:8080
```
**Expected behavior:**
First start creates all files

**Logs:**

```
today at 19:29:22postgres: could not access the server configuration file "/config/postgres/postgresql.conf": No such file or directory
today at 19:29:22/var/run/postgresql:5432 - no response
today at 19:29:22Waiting for postgres to come up...
```

**Screenshots:**

**Environment:**

* **Guacamole Version**:  1.4.0-s6_v3
* **Operating System**: Docker

**Comment by abesnier** [comment]
Hello quorn23

Sorry to see that. 
What is the expected value of ${DOCKERCONFDIR}?
What happens if you replace ${DOCKERCONFDIR}/config with another path?
Can you start the container with a command line, for example `docker run -d -v "config:/config" --name testguac abesnier/guacamole`?
For all I have tested, the issue would be that there is an issue with access right to the host folder. If the config directory does not exist, start the container as root (add  `user: root` in `docker-compose.yml`, or use `-u root` for `docker run`). This will make sure the configuration from the image is created in the host.

**Comment by abesnier** [comment]
Hello @quorn23 
Did you give a try with -u root?
May I close the issue?

**Comment by doodie** [comment]
RH 8.5
Docker version 20.10.12, build e91ed57

I am having the same issue. Ran as root, both manually and as a stack.

`docker run \
>   -p 8080:8080 \
>   -u root \
>   -v /opt/guacamole:/config \
>   abesnier/guacamole`

`  version: "3"
  services:
    guacamole:
      image: abesnier/guacamole
      container_name: guacamole
      user: root
      volumes:
        - /opt/guacamole:/config
      ports:
        - 8080:8080
        `

i tried fixing ownership to root adjusting permissions, but after a restart, it reverts back
`root@elder:/opt/guacamolell
total 0
drwxr-xr-x 6 root root 105 Feb 11 22:08 guacamole
drwx------ 2  103  105   6 Feb 11 22:08 postgres`

test container came back with same issue

**Comment by abesnier** [comment]
Hi @doodie 

Really sorry to see that. 
After some investigation, I believe the root cause is an issue with s6 overlay. The script that is supposed to check if postgres is setup or not does not run.
I have a few ways to bypass this issue, I will let you know.
If that does not work, I will revert to s6 overlay 2.2.0.3, as the issue is with the way s6 overlay 3 handles the init scripts.

**Comment by abesnier** [comment]
I confirm I cannot make it work with the current release of S6 overlay. I already had issues that were fixed, and obviously the fix does not work anymore with the latest release. I am quite disappointed.

I will revert to s6 overlay 2.2.03, and notify you when the image is pushed.

**Comment by quorn23** [comment]
> Hello @quorn23 Did you give a try with -u root? May I close the issue?

Apologizes for my late answer, life was busy.  

I can confirm the reported behavior of doodie and the your updated image is working now.

Thanks for looking into it.

I will close the issue as it's solved :)
