### ISSUE TITLE
guacamole.mydomain.com -> mydomain.com/guacamole

### ISSUE THREAD

**Issue by jesb1n** [abesnier/docker-guacamole#36]
As the title suggests I want to access the guacamole using a subpath. I tried adding the path in Cloudflare tunnels, but getting a 404 issue.
![image](https://github.com/abesnier/docker-guacamole/assets/52061387/3aaafd01-51ee-46df-8848-48cfb8c93d0f)
 
Renaming ROOT.war to guacamole.war solved my issue. Any ways to make this persistent?

**Comment by abesnier** [comment]
Hi, 

Does your machine serve only Guacamole, or any other services? If so, do you use a reverse proxy?
What you observe is that tomcat is your server, and responds to `mydomain.com`. By default, if you query only `mydomain.com`, it would serve the default `ROOT.war` servlet. If you add /guacamole, it will look for `guacamole.war` servlet, and serve it if found.

If you want queries from guacamole.mydomain.com to be routed to mydomain.com/guacamole, you will need a reverse proxy or a redirect manager.

Because this is containerized application, it basically just runs a service listening to port 8080 on the host machine. All routing have to be managed outside the container.

Have a look at [Nginx proxy manager](https://nginxproxymanager.com/), that's a very convenient tool to manage reverse proxies.

Cheers
Antoine

**Comment by jesb1n** [comment]
Thank you for the reply.
